### ISSUE TITLE
Stopping Bedrock server due to an unhandled exception from vellum...

### ISSUE THREAD

**Issue by mtauberjr** [clarkx86/vellum#29]
vellum v1.2.3 build 157
       by clarkx86 & DeepBlue

Loading configuration "configuration.json"... Done!
Checking for updates... 
Disabling renders because no valid path to a Papyrus executable has been specified
Creating initial world backup...
[         VELLUM         ] Creating backup...
[         VELLUM         ] 	-> Clearing local world backup directory...	
[         VELLUM         ] 	-> Invalid world directory. Could not create full world backup!
[         VELLUM         ] Backup done!
Stopping Bedrock server due to an unhandled exception from vellum...
System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Vellum.Automation.ProcessManager.Start()
   at Vellum.Program.Main(String[] args)
Unhandled exception. System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Vellum.Automation.ProcessManager.Start()
   at Vellum.Program.Main(String[] args)
Aborted (core dumped)

**Comment by mtauberjr** [comment]
had to specify parameters for the config file
