### ISSUE TITLE
Vellum crashes on startup

### ISSUE THREAD

**Issue by samdejong86** [clarkx86/vellum#42]
I'm not sure if this is still being maintained, but I've got an error report. I updated the bedrock server to 1.16.221.01 and when I run vellum, I get this error:

```
vellum v1.3.1 beta build 212
       by clarkx86, DeepBlue & contributors

Loading configuration "configuration.json"... Done!
Reading "server.properties"... Done!
Checking for updates...
Creating initial temporary copy of world directory...
[         VELLUM         ] Executing pre-command...
[         VELLUM         ] Creating backup...
[         VELLUM         ] 	-> Clearing local world backup directory...	
[         VELLUM         ] 	-> Creating full world backup...	
[         VELLUM         ] Backup done!
Stopping BDS due to an unhandled exception from vellum...
System.ComponentModel.Win32Exception (13): Permission denied
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Vellum.Automation.ProcessManager.Start()
   at Vellum.VellumHost..ctor(String[] args)
   at Vellum.VellumHost.Main(String[] args)
Unhandled exception. System.ComponentModel.Win32Exception (13): Permission denied
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Vellum.Automation.ProcessManager.Start()
   at Vellum.VellumHost..ctor(String[] args)
   at Vellum.VellumHost.Main(String[] args)
```

Any idea why?

**Comment by samdejong86** [comment]
Nevermind, I for got to make bedrock_server executable.

**Comment by clarkx86** [comment]
Hey, glad you got it resolved :-)! Just to answer your concern:
> I'm not sure if this is still being maintained
As of now I'm not actively working on this project, but I will still maintain and update vellum in case any breaking bug may occur with an upcoming Bedrock server release in the future.
