### ISSUE TITLE
System.ArgumentNullException during render Windows

### ISSUE THREAD

**Issue by Klowes** [clarkx86/vellum#9]
Program Output:
> [         VELLUM         ]      -> Clearing local world backup directory...
[         VELLUM         ]      -> Creating full world backup...
[         VELLUM         ] Backup done!
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'input')
   at System.Text.RegularExpressions.Regex.Matches(String input)
   at Vellum.Automation.ProcessManager.WaitForMatch(String pattern)
   at Vellum.Automation.BackupManager.CreateWorldBackup(String worldPath, String destinationPath, Boolean fullCopy, Boolean archive)
   at Vellum.Program.InvokeRender(String worldPath, String tempWorldPath)
   at Vellum.Program.<>c__DisplayClass14_1.<Main>b__3(String text)
   at Vellum.Program.<>c.<Main>b__14_2()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Trying to setup a server using this and I'm getting this error while testing this tool.
This happens when running the "force start render" command.

**Comment by Klowes** [comment]
The version I was using was vellum_win-x64_v1.2.1-128. I guess I grabbed this this morning just as you pushed out the new release.

**Comment by Klowes** [comment]
Can confirm that this new version fixes this issue.
